#!/bin/bash
set -ex -o pipefail

if [ ! -e /etc/apt/apt.conf.d/99local ]
then echo 'APT::Install-Recommends "0";' > /etc/apt/apt.conf.d/99local
fi

apt-get update

apt-get install -y \
    build-essential \
    ca-certificates \
    cargo \
    curl \
    fuse \
    git \
    gnupg \
    jq \
    less \
    libffi-dev \
    libssl-dev \
    man \
    python3 \
    python3-dev \
    python3-distutils \
    python3-venv \
    rsync \
    screen \
    tree \
    unzip \
    vim \
    wget \
    zip

apt-get clean
rm -rf /var/lib/apt/lists/*
