#!/bin/bash
set -ex -o pipefail

export PATH="$PATH:$HOME/.local/bin"

if ! command -V pip3 > /dev/null 2>&1
then wget -O- https://bootstrap.pypa.io/get-pip.py | python3 - --user
fi

python3 -m pip install --user --upgrade pip setuptools wheel
python3 -m pip install --user --upgrade datalad pre-commit tox
