#!/bin/bash
set -ex -o pipefail

export PATH="$PATH:$HOME/.local/bin"

cd ~
[ -e datalad-fuse ] || git clone -b gh-7 https://github.com/datalad/datalad-fuse

mkdir -p fuse-test/mount
cd fuse-test
[ -e highspeed-bids ] \
    || datalad clone https://gin.g-node.org/lnnrtwttkhn/highspeed-bids
